### ISSUE TITLE
Dead M28's still spam errors about nuke locations

### ISSUE THREAD

**Issue by VaelophisNyx** [maudlin27/M28AI#110]
error in question:
```
`false, "M28ERROR Count=16776477: GameTime 4081: Potential infinite loop, aborted recording nuke missile location", "M28ERROR Count=16776477: GameTime 4081: Potential infinite loop, aborted recording nuke missile location
stack traceback:
	[C]: in function `assert'
	[C]: in function `pcall'
	...r forged alliance\mods\m28ai\lua\ai\m28utilities.lua(55): in function `ErrorHandler'
	...er forged alliance\mods\m28ai\lua\ai\m28building.lua(4148): in function `RecordNukeTarget'
	...nder forged alliance\mods\m28ai\lua\ai\m28events.lua(1004): in function `OnWeaponFired'
	...aforever\gamedata\lua.nx2\lua\sim\defaultweapons.lua(59): in function `OnWeaponFired'
	...\lua.nx2\lua\sim\weapons\defaultprojectileweapon.lua(1100): in function <...\lua.nx2\lua\sim\weapons\defaultprojectileweapon.lua:963>"`
```

Log file:
https://drive.google.com/file/d/1j3rhfuCpuSVRROpyr0py6lV_98-rdaYT/view?usp=sharing File too large for Github or Pastebin

**Comment by VaelophisNyx** [comment]
for context, this M28 went up against 1 Uveso Rush, 1 Uveso Experimentals, and 1 Uveso Adaptive. 2 Aeon, 1 Seraphim. It died VERY early on, something I was a bit shocked to see, given lackluster performance from Uveso in the recent past

**Comment by VaelophisNyx** [comment]
This error also gets spammed when >1 nuke is fired in a single beat/tick
consistently. This freezes the sim permanently.

**Comment by maudlin27** [comment]
Thanks, from memory this error was fixed shortly after the above
