### ISSUE TITLE
AI fears mobile missile launchers too much

### ISSUE THREAD

**Issue by SissiHermanni** [maudlin27/M28AI#116]
Using army of T2 mobile missile launchers makes AI to pull all its ground forces back outside of missile launchers range instead of attacking them, even if it has sizeable army to attack and destroy those launchers without any problem. Because of this, player can just keep pushing it and destroy it's eco almost without any fight, If player is too slow with pushing or doesn't have air control, AI will counter attack with bombers and gunships, if it has any left,

**Comment by maudlin27** [comment]
I'd need a replay to check - M28 is meant to attack the MMLs if it has a significantly stronger ground force (e.g. its tanks are more than the enemy by a significant margin, such as more than 2:1)
