### ISSUE TITLE
No SMD

### ISSUE THREAD

**Issue by splitice** [maudlin27/M28AI#128]
We played a game with M28 AIX.

Won massively because the AI did not build any SMD.

Game was quite fast in the late game though so well done. Just once we realised... the game was over.

**Comment by maudlin27** [comment]
I'd need a replay to consider further; also FYI better to message me on discord or post in the AI development discord as I rarely see github notifications

**Comment by maudlin27** [comment]
Closing as I expect this will no longer be relevant (there have been changes to the SMD construction decision since early May, and I'd need a replay to consider further)
